sonar.verbose=true
sonar.organization=muraliinaya
sonar.projectKey=muraliinaya_muralitrend
sonar.projectName=muralitrend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
