sonar.verbose=true
sonar.organization=muraliinaya
sonar.projectKey=muraliinaya_muralitrend
sonar.projectName=muralitrend

sonar.sourceEncoding=UTF-8

# Source code
sonar.sources=src/main/java

# Test code
sonar.tests=src/test/java

# Compiled classes
sonar.java.binaries=target/classes

# JaCoCo coverage
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

